Raymaker.MultiSelect/Models/Car.cs
namespace Raymaker.MultiSelect.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Doors { get; set; }
        public string Colour { get; set; }
        public decimal Price { get; set; }
    }
}

Raymaker.MultiSelect/Models/CustomerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace Raymaker.MultiSelect.Models
{
    public class CustomerModel
    {
        [BindProperty]
        [Required]
        public string CustomerName { get; set; }

        [BindProperty, DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }

        [BindProperty]
        [Required]
        public List<string> Toppings { get; set; }
    }
}

Raymaker.MultiSelect/Models/Delivery.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace Raymaker.MultiSelect.Models
{
    public class Delivery
    {
        [BindProperty]
        public decimal Price { get; set; }
        public DateTime DeliveryDate { get; set; }
        public string Address { get; set; }
    }
}

Raymaker.MultiSelect/Models/EmailOptions.cs
namespace Raymaker.MultiSelect.Models
{
    public class EmailOptions
    {
        public string EmailFrom { get; set; }
        public string EmailDisplayName { get; set; }
        public string EmailSmtp { get; set; }
    }
}

Raymaker.MultiSelect/Models/PizzaOptions.cs
using System.Collections.Generic;

namespace Raymaker.MultiSelect.Models
{
    public class PizzaOptions
    {
        public List<string> Toppings { get; set;}
        public Delivery Delivery { get; set; }
    }
}

Raymaker.MultiSelect/Pages/CarList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Raymaker.Pages
{
    public class CarListModel : PageModel
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Colour { get; set; }
        public int Doors { get; set; }
        public int Price { get; set; }
        
        public void OnGet()
        {
        }
    }
}

Raymaker.MultiSelect/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Raymaker.MultiSelect.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            this._logger = logger;
        }

        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Raymaker.MultiSelect/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Raymaker.MultiSelect.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            this._logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Raymaker.MultiSelect/Pages/Legacy.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Raymaker.MultiSelect.Pages
{
    public class LegacyModel : PageModel
    {
        private readonly ILogger<LegacyModel> _logger;

        public LegacyModel(ILogger<LegacyModel> logger)
        {
            this._logger = logger;
        }

        public void OnGet([FromQuery(Name = "EmpNo")] string empNo, [FromQuery(Name = "Date")] DateTime date)
        {
            
        }
    }
}

Raymaker.MultiSelect/Pages/List.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using Raymaker.MultiSelect.Models;

namespace Raymaker.MultiSelect.Pages
{
    public class ListModel : PageModel
    {
        private readonly PizzaOptions options;
        
        public ListModel(IOptions<PizzaOptions> options)
        {
            this.options = options.Value;
        }

        [BindProperty]
        public CustomerModel Customer { get; set; }

        [BindProperty]
        public Delivery Delivery { get; set; }

        public void OnGet()
        {
            ViewData["PizzaToppings"] = new SelectList(this.options.Toppings);
            Delivery = this.options.Delivery;
        }

        public void OnPostSubmit()
        {
            // Order the pizza
        }
    }
}

Raymaker.MultiSelect/Pages/Privacy.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Raymaker.MultiSelect.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            this._logger = logger;
        }

        public void OnGet([FromQuery(Name = "EmpNo")] string empNo, [FromQuery(Name = "Date")] DateTime date)
        {
            
        }
    }
}

Raymaker.MultiSelect/Pages/CarList.cshtml
@page
@model Raymaker.Pages.CarListModel
@{
}

<div class="row" id="content">
    <div class="col-lg-6">
        <h3>All Cars</h3>
        <ul id="car-list"></ul>
        <button class="btn btn-sm btn-default" id="new">Add New</button>
    </div>
    <div class="col-lg-6">
        <div id="details"></div>
        <div id="form">
            <form class="form-horizontal">
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label for="Model">Make</label>
                    <input type="text" asp-for="Make" class="form-control input-sm" />
                </div>
                <div class="form-group">
                    <label for="Model">Model</label>
                    <input type="text" asp-for="Model" class="form-control input-sm" />
                </div>
                <div class="form-group">
                    <label for="Colour">Colour</label>
                    <input type="text" asp-for="Colour" class="form-control input-sm" />
                </div>
                <div class="form-group">
                    <label for="Year">Year</label>
                    <input type="number" asp-for="Year" class="form-control input-sm" />
                </div>
                <div class="form-group">
                    <label for="Doors">Doors</label>
                    <input type="number" asp-for="Doors" class="form-control input-sm" />
                </div>
                <div class="form-group">
                    <label for="Price">Price</label>
                    <input type="number" asp-for="Price" class="form-control input-sm" />
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-sm" id="save">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

Raymaker.MultiSelect/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Raymaker.MultiSelect/Pages/List.cshtml
@page

@model Raymaker.MultiSelect.Pages.ListModel
@{
    ViewData["Title"] = "Order Pizza";
}


<div class="jumbotron">
    <h1>Bootstrap Multiselect</h1>
    <p>See also <a href="http://davidstutz.github.io/bootstrap-multiselect/">http://davidstutz.github.io/bootstrap-multiselect/</a></p>

    <form method="post">
        <div class="form-group">
            <label asp-for="Customer.CustomerName">Customer Name</label>
            <input asp-for="Customer.CustomerName" class="form-control" />
            <span asp-validation-for="Customer.CustomerName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Customer.BirthDate">Birth date</label>
            <input asp-for="Customer.BirthDate" asp-format="{0:yyyy-MM-dd}" class="form-control mw-250" />
        </div>

        <div class="form-group">
            <label for="example-getting-started">Select Toppings</label>
            <br />

            <!-- Build your select: -->
            <select id="example-getting-started" asp-for="Customer.Toppings" multiple="multiple" 
                    class="form-control bg-warning" asp-items="ViewBag.PizzaToppings">
            </select>

            <small id="groceryHelp" class="form-text text-muted">Please select some items from the above list.</small>
        </div>

        <div class="form-group">
            <span>Delivery is available for @string.Format("{0:c}", Model.Delivery.Price)</span>
        </div>

        <input type="submit" class="btn btn-primary" value="Submit" asp-page-handler="Submit" />
        <a class="btn btn-danger" asp-page="/List">Reset</a>
    </form>

    @if (Model.Customer != null)
    {
        <p>
            <span>@Model.Customer.CustomerName ordered @string.Join(",", Model.Customer.Toppings)</span>
        </p>
    }

</div>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />

    <!-- Initialize the plugin: -->
    <script type="text/javascript">
        $(document).ready(function () {
            $('#example-getting-started').multiselect(
                {
                    enableHTML: false,              // prevent XSS (default set to false)
                    inheritClass: true,             // show button class
                    numberDisplayed: 2,             // max number of options to display
                    includeSelectAllOption: true    // includes a select all option at the top
                });
        });
    </script>
}

Raymaker.MultiSelect/Pages/Shared/_Header.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-page="/Index">
            <img src="~/images/microsoft-net-logo.png" alt="site-logo" class="navbar-logo"/>RazorPages Demo
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <p class="nav navbar-text navbar-right user-login">
                <svg class="icon" enable-background="new 0 0 500 500" id="Layer_1" version="1.1" viewBox="0 0 500 500" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g><g><path d="M250,291.6c-52.8,0-95.8-43-95.8-95.8s43-95.8,95.8-95.8s95.8,43,95.8,95.8S302.8,291.6,250,291.6z M250,127.3    c-37.7,0-68.4,30.7-68.4,68.4s30.7,68.4,68.4,68.4s68.4-30.7,68.4-68.4S287.7,127.3,250,127.3z"/></g><g><path d="M386.9,401.1h-27.4c0-60.4-49.1-109.5-109.5-109.5s-109.5,49.1-109.5,109.5h-27.4c0-75.5,61.4-136.9,136.9-136.9    S386.9,325.6,386.9,401.1z"/></g></g></svg>

                Hello, @User.Identity.Name!
            </p>
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-page="/Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-page="/List">Order Pizza</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-page="/Privacy">Privacy</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-page="/Legacy">Legacy</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Raymaker.MultiSelect/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MultiSelect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap-multiselect/dist/css/bootstrap-multiselect.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
    <header>
        <partial name="_Header" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - MultiSelect Demo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-multiselect/dist/js/bootstrap-multiselect.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", false)
</body>
</html> 